apiVersion: apps/V1
kind: Deployment
metadata:
  name: user-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchlabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: user-service
          image: acrempcalories.azurecr.io/user-service:#{Build.BuildId}#
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8097
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
    k8s-app: user-service
  name: user-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8090
  selector:
    app: user-service